---
version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    build: .
    ports:
      - "8001:80"
    depends_on:
      - db
    volumes:
      - ./api:/app/api
    environment:
      MODULE_NAME: "api.main"
      POSTGRES_URL: $POSTGRES_URL
    env_file: .env
    entrypoint: /start-reload.sh # For dev only - adds hot-reloading
volumes:
  db-data: null
  pgadmin-data: null
