---
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
  #     PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
  #     PGADMIN_LISTEN_PORT: $PGADMIN_LISTEN_PORT
  #   ports:
  #     - '8081:80'
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   links:
  #     - db:pgsql-server
  web:
    build: .
    ports:
      - '8001:80'
    environment:
      POSTGRES_URL: $POSTGRES_URL
    depends_on:
      - db
    volumes: 
      - ./api:/app/api
    environment:
      MODULE_NAME: "api.main"
      POSTGRES_URL: $POSTGRES_URL
    entrypoint: /start-reload.sh # For dev only - adds hot-reloading
volumes:
  db-data: null
  pgadmin-data: null